// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestDNFullTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
        driver = new ChromeDriver(@"C:\Users\PhatTai\Desktop\Nhom07_KiemChungWebsiteBanQuanAo\Nhom07_KiemChungWebsiteBanQuanAo\TestShopQuanAo");
        js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  public void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testDNFull() {
    driver.Navigate().GoToUrl("http://localhost:27660/TaiKhoan/DangNhap");
    driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
    driver.FindElement(By.Name("username")).SendKeys("TK005");
    driver.FindElement(By.Name("pw")).SendKeys("123");
    driver.FindElement(By.Id("btnSignin")).Click();
      
    driver.FindElement(By.CssSelector(".header__top__links:nth-child(2) > a")).Click();
        Thread.Sleep(3000);
    }
    public void testDNFull(string pUsername, string pPw)
    {
        driver.Navigate().GoToUrl("http://localhost:27660/TaiKhoan/DangNhap");
        driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
        driver.FindElement(By.Name("username")).SendKeys(pUsername);
        driver.FindElement(By.Name("pw")).SendKeys(pPw);
        driver.FindElement(By.Id("btnSignin")).Click();
        Thread.Sleep(3000);
        driver.FindElement(By.CssSelector(".header__top__links:nth-child(2) > a")).Click();
        Thread.Sleep(3000);
    }
}
